steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github_traverse', '.']
    timeout: 300s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github_traverse']
    timeout: 300s
timeout: 600s
images: ['gcr.io/$PROJECT_ID/github_traverse']
